services:
  ytcomments:
    build:
      context: ../../
      dockerfile: install/docker/Dockerfile
    container_name: ytcomments_service
    ports:
      - "27017:27017"
      - "9093:9093"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ../../.env

volumes:
  mongo-data:
    driver: local